### ISSUE TITLE
Block does not stop after timeout

### ISSUE THREAD

**Issue by nmagerko** [glenfant/stopit#19]
I am using version 1.1.2 with Python 3.7. 

My goal is to use this module to wrap a call to the Python Docker SDK's `wait` function so that I can determine whether a container finishes executing within a timeout, and kill the container if it continues executing beyond that timeout. 

I have code that looks like this:

```python
container =  # ... a detached docker container
with stopit.ThreadingTimeout(10) as timeout_ctx:
    assert timeout_ctx.state == timeout_ctx.EXECUTING
    container.wait()  # blocking call

if timeout_ctx.state == timeout_ctx.EXECUTED:
  print("Executed within timeout")
elif timeout_ctx.state == timeout_ctx.TIMED_OUT:
  print("Executed beyond timeout")
```

For containers that run beyond the (10 second) timeout above, I see `Executed beyond timeout` as I'd expect. However, the `wait()` call continues blocking until the container finishes (which could be much more time than 10 seconds).

Is this expected behavior?

**Comment by glenfant** [comment]
Hi,

If `container.wait()` is really blocking and lock the Python GIL, you can consider this is the expected behaviour, as explained in the doc about stopit limitations.

You should perhaps try the `timeout` keyword arg of  `container.wait()`.

https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.wait
