### ISSUE TITLE
stopit not timing out while opening file

### ISSUE THREAD

**Issue by asbjornb** [glenfant/stopit#24]
Hi,

On windows 10 stopit doesn't seem to timeout at all when doing file reads with pyarrow.Parquet. This works fine for me:
```
import stopit
import pyarrow.parquet as pq

def infiniteloop():
    with stopit.ThreadingTimeout(5) as to_ctx_mgr:
        assert to_ctx_mgr.state == to_ctx_mgr.EXECUTING
        while True:
            pass
    print(str(to_ctx_mgr.state))
    return False

infiniteloop()
```
however this:
```
import stopit
import pyarrow.parquet as pq

def ReadMetaFromDataset(filepath):
    with stopit.ThreadingTimeout(5) as to_ctx_mgr:
        assert to_ctx_mgr.state == to_ctx_mgr.EXECUTING
        schema = pq.ParquetDataset(filepath).schema
        return schema
    print(str(to_ctx_mgr.state))
    return False

ReadMetaFromDataset(r"\\lcdevnas01\development\ENav2")
```
and this:
```
import stopit.threading_timeoutable
import pyarrow.parquet as pq

@threading_timeoutable(default='not finished')
def ReadMetaFromDataset(filepath):
    with stopit.ThreadingTimeout(10) as to_ctx_mgr:
        assert to_ctx_mgr.state == to_ctx_mgr.EXECUTING
        schema = pq.ParquetDataset(filepath).schema
        return schema
    print(str(to_ctx_mgr.state))
    return False

print(ReadMetaFromDataset(r"\\lcdevnas01\development\ENav2", timeout=5))
```
runs to completion after 90 minutes. Anything I can do with stopit to force timeouts or do I have to look into threading and kill from a separate process?

Thanks
Asbjorn

**Comment by glenfant** [comment]
Hi !
It seems that your example matches one of the limitations of stopit due to limitations of Python threading model. This limitation is clearly described in the README.
pyarrow.paquet is a Python binding over a C / C++ library that locks the threads as most bindings do, thus the special exception raised has no effect since thread switching is locked while such code is running.
With a Linux / MacOS box, you could use the SignalTimeout.
Since I have no Windows box, I cannot explore other solutions.
